name: Cypress Tests

on:
  # runs tests every day at 4am
  #schedule:
    # - cron: '*/15 * * * *' # runs every 15th minute
  # - cron: '0 4 * * *'
   [ push ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001

    strategy:
      fail-fast: false


    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16


      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run tests-org4


